version: "3.7"

services:
  mongodb:
    image: mongo:4.0.6
    ports:
      - "${LOCAL_DB_PORT}:27017"
    volumes:
      - "sports-mongodb-data:${LOCAL_DB_VOLUME_PATH}"

volumes:
  sports-mongodb-data: