version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "sports-mysql-data:/c/work/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sports
    ports:
      - "3306:3306"

volumes:
  sports-mysql-data: